source = $HOME/.config/hypr/config/variables.conf

# DIALOG WINDOW RULES
windowrule = float on, match:title ^(Open File)(.*)$
windowrule = float on, match:title ^(Select a File)(.*)$
windowrule = float on, match:title ^(Choose wallpaper)(.*)$
windowrule = float on, match:title ^(Open Folder)(.*)$
windowrule = float on, match:title ^(Save As)(.*)$
windowrule = float on, match:title ^(Library)(.*)$
windowrule = float on, match:title ^(File Upload)(.*)$
windowrule = float on, match:title ^(File Operation Progress)$
windowrule = float on, match:title ^(Confirm to replace files)$
windowrule = float on, match:class ^($browser)$, match:title .*accounts.*

# File diav2logs with specific sizes
windowrule = size 800 600, match:class ^(firefox|google-chrome|zen)$, match:title ^(Save As)$
windowrule = size 800 600, match:class ^(firefox|google-chrome|zen)$, match:title ^(Choose Files)$
windowrule = size 800 600, match:class ^(firefox|google-chrome|zen)$, match:title ^(Open File)$
windowrule = size 800 600, match:class ^(firefox|google-chrome|zen)$, match:title ^(Open Folder)$

# APPLICATION-SPECIFIC DIALOGS
# qView image viewer
windowrule {
    name = qview-optimization
    match:class = ^(com.interversehq.qView)$

    # Efectos
    # Truco para engañar a la app sobre su estado de pantalla completa
    # Indica al compositor que es contenido fotográfico (mejora colores/latencia)
    opaque = on
    #keep_aspect_ratio = on
}
