source = $HOME/.config/hypr/config/variables.conf

# FLOATING WINDOW RULES

windowrule = float on, match:class ^($terminal)$, match:title ^(top)$
windowrule = float on, match:class ^($terminal)$, match:title ^(btm)$
windowrule = float on, match:class ^($terminal)$, match:title ^(htop)$

windowrule = float on, match:class ^([Tt]hunar)$, match:title ^(Rename.*)$
windowrule = float on, match:class ^([Ss]team)$ 
windowrule = float on, match:class ^(VirtualBox.*)$ 
windowrule = float on, match:class ^(org.gnome.FileRoller)$

windowrule = float on, match:class ^(xdg-desktop-portal-gtk|qt[56]ct|nwg-look|nwg-displays|gnome-calculator)$

windowrule = float on, match:class ^(org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor|mpv|com.github.wwmm.easyeffects)$

# --- Multimedia y Otros ---
# Nota: qView ya lo definimos en el bloque anterior con tamaño específico, 
# pero no pasa nada por dejarlo aquí también para asegurar que flote.
windowrule = float on, match:class ^(org.Waytrogen.Waytrogen|waytrogen)$
windowrule = float on, match:class ^(com.github.unrud.VideoDownloader)$
windowrule = float on, match:class ^(com.interversehq.qView)$

#windowrule = size 1280 720, match:class ^(mpv)$

#windowrule = center on, match:class ^(mpv)$

windowrule {
  name = menu-peaclock
  match:class = ^(peaclock-drop)$
  
  float = on
  border_size = 0
  size = 450 250
  
  # Usamos la nueva sintaxis de expresiones matemáticas (monitor_w)
  move = ((monitor_w*0.5)-225) 40
  pin = on
  animation = slide top
}

windowrule {
  name = menu-calcure
  match:class = ^(calcure-drop)$
  
  float = on
  border_size = 0
  size = 300 250
  
  move = ((monitor_w*0.5)-150) 40
  pin = on
  animation = slide top
}
