source = $HOME/.config/hypr/config/variables.conf
# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Arreglo para problemas de arrastre en XWayland (Fix XWayland drags)
# Al tener muchas condiciones, usamos el formato de BLOQUE para que no falle.
windowrule {
    name = fix-xwayland-ghosts
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    
    no_focus = on
}

# Desactivar blur en ventanas vacías (evita glitches visuales)
windowrule = no_blur on, match:class ^$, match:title ^$