source = $HOME/.config/hypr/config/variables.conf

# LAYER RULES
layerrule = blur on, match:namespace wofi
layerrule = xray on, match:namespace wofi
layerrule = dim_around on, match:namespace wofi
layerrule = ignore_alpha 0.9, match:namespace wofi

# --- HYPRSWITCH (Cambiador de ventanas) ---
# 'noanim' ahora es 'no_anim'
layerrule = no_anim on, match:namespace hyprswitch
layerrule = no_anim on, match:namespace mpv


# --- WAYBAR (Barra Superior) ---
# He descomentado esto y arreglado la sintaxis (blur_popups lleva guion bajo)
layerrule = blur on, match:namespace waybar
layerrule = xray on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar
# Si quieres efecto borroso detrás (opcional)
#
## --- SWAYNC (Notificaciones) ---
## Aplica a la ventana de notificación y al centro de control
#layerrule = blur on, match:namespace swaync-notification-window
#layerrule = blur on, match:namespace swaync-control-center
#
#layerrule = xray on, match:namespace swaync-notification-window
#layerrule = xray on, match:namespace swaync-control-center
#
#layerrule = ignore_alpha 0.45, match:namespace swaync-control-center
#layerrule = ignore_alpha 0.45, match:namespace swaync-notification-window
#
## Animación específica para el panel lateral
#layerrule = animation slide right, match:namespace swaync-control-center
#
## --- LOGOUT (Salida) ---
#layerrule = blur on, match:namespace logout_dialog
