source = $HOME/.config/hypr/config/variables.conf

# PICTURE-IN-PICTURE (PIP) RULES
windowrule {
    name = pip-rules
    
    # 1. Selectores: Navegadores + Título PiP
    match:class = ^(firefox|google-chrome|zen)$
    match:title = ^.*(Picture-in-Picture|Picture in Picture).*$

    # 2. Efectos
    float = on
    pin = on              # Pin para que se vea en todos los workspaces
    size = 480 270        # Tamaño fijo pequeño
    no_blur = on          # Sin borrosidad (ahorra recursos)
    move = 74.5% 4.25%    # Posición en pantalla (esquina superior derecha aprox)
    animation = slide     # Animación específica
    opaque = on           # Totalmente opaco
}
windowrule = monitor $mainMonitor, match:class ^(mpv)$

#windowrule = center on, match:class ^(mpv)$

windowrule {
  name = menu-peaclock
  match:class = ^(peaclock-drop)$
  
  float = on
  border_size = 0
  size = 450 250
  
  # Usamos la nueva sintaxis de expresiones matemáticas (monitor_w)
  move = ((monitor_w*0.5)-225) 40
  pin = on
  animation = slide top
}

windowrule {
  name = menu-calcure
  match:class = ^(calcure-drop)$
  
  float = on
  border_size = 1
  size = 300 250
  
  move = ((monitor_w*0.5)-150) 40
  pin = on
  animation = slide top
}

windowrule {
  name = cava-drop-left
  match:class = ^(cava-drop-left)$
  
  float = on
  border_size = 1

  size = (monitor_w*0.25) 250
  move = 5 40

  pin = on
  animation = slide top
}


windowrule {
  name = cava-drop-right
  match:class = ^(cava-drop-right)$
  
  float = on
  border_size = 1

  size = (monitor_w*0.25) 250
  move = ((monitor_w)-(monitor_w*0.25)-5) 40

  pin = on
  animation = slide top
}



