source = $HOME/.config/hypr/config/variables.conf

# OPACITY WINDOW RULES
windowrule = opacity $opacityFloat $opacityFloat, match:class ^(hyprswitch|thunar|code|cursor|kiro-url-handler)$

# Special opacity for typing test
# Forzar opacidad 1.0 (sólido) siempre para navegadores
windowrule {
    name = browser-force-solid
    match:class = ^(zen-browser|firefox|google-chrome|zen|helium)$
    
    # Usamos override para que no se mezcle con nada más
    opacity = 1.0 override 1.0 override
    no_dim = on
}


windowrule {
    name = office-force-solid
    match:class = ^(ONLYOFFICE|libreoffice-writer)$
    
    # Usamos override para que no se mezcle con nada más
    opacity = 1.0 override 1.0 override
    no_dim = on
}

windowrule{
  name = youtube-force-transparent
  match:class= ^(com.github.th_ch.youtube_music)$

  opacity = 0.8 override 0.75 override
}

#windowrule {
#    name = code-force-transparent
#    match:class = ^(codium)$
#    
#    # Usamos override para que no se mezcle con nada más
#    opacity = 0.96 override 0.96 override
#    no_dim = on
#}

# 2. Excepción: Monkeytype en Zen (Transparente)
# Esta regla DEBE ir debajo de la anterior para sobrescribirla
windowrule {
    name = monkeytype-focus
    
    match:class = ^(zen|zen-browser)$
    # Simplificamos el título para que coincida con cualquier pestaña que empiece por Monkeytype
    match:title = ^(Monkeytype.*)$
    
    # Forzamos 0.75 aunque la regla de arriba diga 1.0
    opacity = 0.9 override 0.9 override
}
