hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal .. " -e tmux"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("~/.config/rofi/powermenu/powermenu.sh"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("kitty yazi"))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(musicPlayer))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd("~/.config/scripts/system/reload_shell.sh"))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(launcher))
hl.bind("XF86Calculator", hl.dsp.exec_cmd(calculator))
