# APPLICATION KEYBINDINGS

bind = $mainMod, B, exec, $browser
bind = $mainMod, RETURN, exec, $terminal 
bind = $mainMod, T, exec, $terminal -e tmux
bind = $mainMod, O, exec, ~/.config/rofi/powermenu/powermenu.sh
bind = $mainMod, M, exec, $fileManager
bind = $mainMod, E, exec, kitty yazi
bind = $mainMod, Y, exec, $musicPlayer
bind = $mainMod, P, exec, hyprpicker -a
bind = $mainMod CTRL, R, exec, waybar
bind = $mainMod, Space, exec, $launcher
bind = , XF86Calculator, exec, $calculator
