# APPLICATION KEYBINDINGS

bind = $mainMod, B, exec, $browser
bind = $mainMod, T, exec, $terminal
bind = $mainMod, O, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, M, exec, $fileManager
bind = $mainMod, E, exec, $terminal yazi
bind = $mainMod, Y, exec, $musicPlayer
bind = $mainMod, Space, exec, $launcher
bind = , XF86Calculator, exec, $calculator
