# MEDIA & SYSTEM KEYBINDINGS

bindel = , XF86AudioRaiseVolume, exec, $volumeBrightness volume_up
bindel = , XF86AudioLowerVolume, exec, $volumeBrightness volume_down
bindel = , XF86AudioMute, exec, $volumeBrightness volume_mute
bindel = , XF86AudioMicMute, exec, $volumeBrightness mic_mute
bindel = , XF86MonBrightnessUp, exec, $volumeBrightness brightness_up
bindel = , XF86MonBrightnessDown, exec, $volumeBrightness brightness_down
bindl = , XF86AudioPlay, exec, $volumeBrightness play_pause
bindl = , XF86AudioPause, exec, $volumeBrightness play_pause
bindl = , XF86AudioPlayPause, exec, $volumeBrightness play_pause
bindl = , XF86AudioNext, exec, $volumeBrightness next_track
bindl = , XF86AudioPrev, exec, $volumeBrightness prev_track

# SCREENSHOTS
bind = , Print, exec, ~/.config/scripts/utils/screenshot.sh -r selection
