# ANIMATION CONFIGURATION

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = true, animations

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = overshoot, 0.05, 0.9, 0.1, 1.1
    bezier = backIn, 0.5, -0.5, 0.5, 1.5
    bezier = easyBackIn, 0.8, -0.2, 0.8, 1.0

    # Default animations, see https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        0,     10,    linear
    animation = border,        0,     5.39,  linear 
    animation = windows,       0,     3.1,   linear
    animation = windowsIn,     0,     3.1,   linear
    animation = windowsOut,    0,     2.49,  linear
    animation = windowsMove,   0,     2.1,   linear
    animation = fade,          0,     3.03,  linear
    animation = fadeIn,        0,     5.73,  linear
    animation = fadeOut,       0,     5.46,  linear
    animation = layers,        0,     3.81,  linear
    animation = layersIn,      0,     3.5,     linear
    animation = layersOut,     0,     2.5,   linear
    animation = fadeLayersIn,  0,     1.79,  linear
    animation = fadeLayersOut, 0,     1.39,  linear
    animation = workspacesOut, 0,     $animSpeed,  linear
    animation = workspaces,    1,     $animSpeed,  linear
    animation = zoomFactor,    1,     $animSpeed,     linear
}
