# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

scrolling {
    # El ancho por defecto de cada ventana nueva (0.5 = mitad de la pantalla)
    column_width = 0.7 
    
    # Si solo hay 1 ventana, ocupa toda la pantalla automáticamente
    fullscreen_on_one_column = true 
    
    # Hacia dónde crece la cinta al abrir nuevas ventanas (right = derecha)
    direction = right 
    
    # Comportamiento del enfoque
    follow_focus = true
    focus_fit_method = 1   # 0 = centrar la ventana al enfocarla, 1 = ajustarla
    
    # Tamaños predefinidos para cuando redimensiones con el teclado
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
}



