source = $HOME/.config/hypr/config/variables.conf
source = $HOME/.config/hypr/monitors.conf


preload = $wallpaperDir
$wallpaper = $wallpaperDir/dungeon.png


wallpaper {
    monitor = $mainMonitor
    path = $wallpaper
    fit_mode = cover
}
wallpaper {
    monitor = $secondaryMonitor
    path = $wallpaperDir/kenny.png
    fit_mode = cover
}


splash=false
