
$wallpaperDir = ~/Pictures/Wallpapers

$wallpaper = $wallpaperDir/shirohige_inverted.png




wallpaper {
    monitor = "DP-2"
    path = $wallpaper
    fit_mode = cover
}
wallpaper {
    monitor = "HDMI-A-1"
    path = $wallpaperDir/roger_inverted.png
    fit_mode = cover
}


splash=false
