
$wallpaperDir = ~/Pictures/Wallpapers

$wallpaper = $wallpaperDir/roger_inverted.png


wallpaper {
    monitor = eDP-1
    path = $wallpaper
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = $wallpaperDir/hands.png
    fit_mode = cover
}


splash=false
