hl.config({ autogenerated = false })

-- 1. Variables Globales y Monitores
require("variables")
require("monitors")

-- 2. Módulos Core
require("config.environment")
require("config.autostart")
require("config.appearance")
require("config.animations")
require("config.layouts")
require("config.input")
require("config.plugins")

-- 3. Atajos de Teclado
require("keybinds.applications")
require("keybinds.media")
require("keybinds.windows")
require("keybinds.workspaces")

-- 4. Reglas
require("rules.general")
require("rules.floating")
require("rules.dialogs")
require("rules.media")
require("rules.opacity")
require("rules.layers")
