# HYPRLAND MONITOR CONFIGURATION

# MONITOR VARIABLES
$mainMonitor = eDP-1
$secondaryMonitor = HDMI-A-2

monitor = $mainMonitor, 1920x1080@144, 0x0, 1
monitor = $secondaryMonitor, 1920x1080@100, 0x0, 1

# ASSING WORKSPACE TO MONITORS

workspace = 1, monitor:$mainMonitor
workspace = 2, monitor:$mainMonitor
workspace = 3, monitor:$mainMonitor
workspace = 4, monitor:$mainMonitor
workspace = 5, monitor:$mainMonitor
workspace = 6, monitor:$mainMonitor
workspace = 7, monitor:$mainMonitor
workspace = 8, monitor:$mainMonitor
workspace = 9, monitor:$mainMonitor
