# HYPRLAND MONITOR CONFIGURATION

monitor = $mainMonitor, 2560x1440@144, 1920x0, 1
monitor = $secondaryMonitor, 1920x1080@100, 0x0, 1

# ASSING WORKSPACE TO MONITORS

workspace = 1, monitor:$secondaryMonitor
workspace = 2, monitor:$secondaryMonitor
workspace = 3, monitor:$secondaryMonitor
workspace = 4, monitor:$secondaryMonitor
workspace = 5, monitor:$secondaryMonitor
workspace = 6, monitor:$secondaryMonitor
workspace = 7, monitor:$secondaryMonitor
workspace = 8, monitor:$secondaryMonitor
workspace = 9, monitor:$secondaryMonitor

workspace = 10, monitor:$mainMonitor
workspace = 11, monitor:$mainMonitor
workspace = 12, monitor:$mainMonitor
workspace = 13, monitor:$mainMonitor
workspace = 14, monitor:$mainMonitor
workspace = 15, monitor:$mainMonitor
workspace = 16, monitor:$mainMonitor
workspace = 17, monitor:$mainMonitor
workspace = 18, monitor:$mainMonitor