# AUTOSTART APPLICATIONS
exec-once =  sed -i 's/"output": .*,/"output": "$mainMonitor",/' ~/.config/waybar/config.jsonc && waybar
exec-once = hyprswitch init --show-title --size-factor 3 --workspaces-per-row 4 --custom-css /home/pbl/.config/hypr/config/hyprswitch.css
exec-once = hyprpaper  
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpm reload -n
exec-once = hyprctl setcursor Bibata-Modern-Classic 16
exec-once = hypridle
#exec-once = swaync
#exec-once = easyeffects --gapplication-service
#exec-once = gnome-keyring-daemon --start --components=secrets
#exec-once = swww init
#exec-once = waytrogen -r


