plugin {
    hyprtasking {
        layout = grid
        gap_size = 15
        border_size = 3
        
        bg_color = 0x3d3a34
        
        # CLAVE: Si es true, al cerrar el overview (Super+Tab) 
        # se seleccionará el workspace sobre el que esté el ratón.
        exit_on_hovered = false

        # Configuración de la matriz 3x3
        grid {
            rows = 3
            cols = 3
        }
        
        # Opcional: para que el ratón no salte de forma brusca
        warp_on_move_window = 1
    }
}

