# bind the reload tmux.conf key
unbind r
bind r source-file ~/.tmux.conf

# set the leader key
set -g prefix C-Space
bind C-Space send-prefix

# enable mouse resize
set -g mouse on

bind \" split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# set vim navigation keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set-option -g status-position top

bind -T copy-mode-vi v send -X begin-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Gruvbox plugin 
#set -g @plugin 'egel/tmux-gruvbox'
#set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
#
#set -g @tmux-gruvbox-statusbar-alpha 'true'
#set -g @tmux-gruvbox-left-status-a '#S' # tmux's session name
#
#set -g @tmux-gruvbox-right-status-x '%d.%m.%Y' # e.g.: 30.01.2024
#set -g @tmux-gruvbox-right-status-y '%I:%M' # 09:54 PM
#set -g @tmux-gruvbox-right-status-z '#h #{tmux_mode_indicator}'

# Minimal theme plugin
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#f5f4d2"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "up"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# expanded icon (fullscreen icon)
set -g @minimal-tmux-expanded-icon "󰊓 "

# on all tabs (default is false)
# false will make it visible for the current tab only
set -g @minimal-tmux-show-expanded-icon-for-all-tabs true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

# To make the selection box rounded () or edged <>
# Default is nothing, when set to true default is edged
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow "█"
set -g @minimal-tmux-left-arrow "█"

# Not recommended to change these values
set -g @minimal-tmux-status-right "#S"
set -g @minimal-tmux-status-left " "

# If getting strings cut in left status or right
# Here 20 is the length of the characters in the string
set -g status-right-length 20
set -g status-left-length 20


run '~/.tmux/plugins/tpm/tpm'
