font_family JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# --- APARIENCIA ---
# Transparencia del fondo (0.1 es invisible, 1.0 es sólido)
background_opacity 0.85

# Quitar la barra de título gris (¡Esto es clave para el look!)
hide_window_decorations yes

# Márgenes internos (para que el texto no toque los bordes)
window_padding_width 20

# --- COMPORTAMIENTO ---
# Evitar que pregunte "¿Seguro que quieres cerrar?" cada vez
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Base2Tone Desert Dark
include current-theme.conf
# END_KITTY_THEME


# --- COMPORTAMIENTO ---
# No pitar (sonido de error)
enable_audio_bell no


